name = "reward-system"
main = "src/index.js"
compatibility_date = "2024-12-01"

# 自定义域名绑定
routes = [
  { pattern = "star.ttgood.cyou", custom_domain = true }
]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "reward-db"
database_id = "a1b41965-9a52-4963-af6b-c57df35e763a"
